"""
hayes_fft_fq.py -- the explicit-formula computation of hayes_fft.py for every small field F_q
(q = p^k <= 16), using the table arithmetic of fqlib.

Group structure. For q = p^k with F_p-basis omega_0..omega_{k-1} (the base-p digits of the
integer encoding), the Hayes group G_l of series 1 + c_1 u + ... (mod u^{l+1}) is the direct
product of the cyclic groups generated by 1 + omega_i u^j, for p not dividing j <= l and
0 <= i < k, each of order p^{s_j} with s_j minimal such that j p^{s_j} > l. (The orders multiply
to q^l, and the greedy reduction below shows that these elements generate.)

Discrete log. Process m = 1..l. If the current coefficient c of u^m is nonzero, write m = j p^a,
let c' = c^{p^{-a}} and expand c' = sum_i e_i omega_i with e_i in F_p. Since
(1 + omega u^j)^{p^a} = 1 + omega^{p^a} u^m and sum_i e_i omega_i^{p^a} = c, multiplying by
prod_i (1 + omega_i u^j)^{-e_i p^a} removes the coefficient of u^m without touching lower ones.

For large groups the L-coefficient arrays are kept in a disk-backed memmap (option work_dir).
"""
from __future__ import annotations

import os
import sys

import numpy as np
from numba import njit

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fqlib  # noqa: E402


def field_info(q):
    A, M, NEG, INV = fqlib.field_tables(q)
    p, k, _ = fqlib.MODULI[q]
    FROB = np.array([0] * q, np.int64)
    for x in range(q):
        y = 1
        for _ in range(p):
            y = int(M[y, x])
        FROB[x] = y
    FINV = np.zeros(q, np.int64)
    for x in range(q):
        FINV[FROB[x]] = x
    return p, k, A, M, NEG, INV, FROB, FINV


def setup(q, l):
    p, k, A, M, NEG, INV, FROB, FINV = field_info(q)
    js, orders = [], []
    for j in range(1, l + 1):
        if j % p == 0:
            continue
        s = 0
        while j * p ** s <= l:
            s += 1
        for i in range(k):
            js.append(j)
            orders.append(p ** s)
    axis_of = np.full((l + 1, k), -1, np.int64)
    t = 0
    for j in range(1, l + 1):
        if j % p == 0:
            continue
        for i in range(k):
            axis_of[j, i] = t
            t += 1
    orders_a = np.array(orders, np.int64)
    strides = np.ones(len(orders), np.int64)
    for i in range(len(orders) - 2, -1, -1):
        strides[i] = strides[i + 1] * orders[i + 1]
    total = 1
    for o in orders:
        total *= o
    assert total == q ** l, (q, l, total)
    return dict(q=q, p=p, k=k, l=l, A=A, M=M, NEG=NEG, INV=INV, FROB=FROB, FINV=FINV,
                axis_of=axis_of, orders=orders_a, strides=strides, shape=tuple(orders))


@njit(cache=True)
def _dlog(series, l, p, k, A, M, NEG, FROB, FINV, axis_of, orders, strides):
    exps = np.zeros(len(strides), np.int64)
    for m in range(1, l + 1):
        c = series[m]
        if c == 0:
            continue
        j = m
        a = 0
        pa = 1
        while j % p == 0:
            j //= p
            a += 1
            pa *= p
        cp = c
        for _ in range(a):
            cp = FINV[cp]
        digits = cp
        for i in range(k):
            e = digits % p
            digits //= p
            if e == 0:
                continue
            ax = axis_of[j, i]
            exps[ax] = (exps[ax] + e * pa) % orders[ax]
            w = 1
            for _ in range(i):
                w = w * p  # integer encoding of omega_i is p^i
            for _ in range(a):
                w = FROB[w]
            # divide series by (1 + w u^m), e times
            for _ in range(e):
                for t in range(m, l + 1):
                    series[t] = A[series[t], NEG[M[w, series[t - m]]]]
    flat = 0
    for i in range(len(strides)):
        flat += exps[i] * strides[i]
    return flat


@njit(cache=True)
def _indices_degree(kdeg, l, q, p, k, A, M, NEG, FROB, FINV, axis_of, orders, strides):
    total = q ** kdeg
    out = np.empty(total, np.int64)
    series = np.zeros(l + 1, np.int64)
    for idx in range(total):
        for i in range(l + 1):
            series[i] = 0
        series[0] = 1
        r = idx
        for i in range(1, kdeg + 1):
            series[i] = r % q
            r //= q
        out[idx] = _dlog(series, l, p, k, A, M, NEG, FROB, FINV, axis_of, orders, strides)
    return out


def class_index(series, ctx):
    s = np.array(series, np.int64)
    return int(_dlog(s.copy(), ctx["l"], ctx["p"], ctx["k"], ctx["A"], ctx["M"], ctx["NEG"],
                     ctx["FROB"], ctx["FINV"], ctx["axis_of"], ctx["orders"], ctx["strides"]))


def square_prefix_series(f, ctx):
    A, M = ctx["A"], ctx["M"]
    d = len(f) - 1
    sq = fqlib.py_mul(list(f), list(f), A, M)
    return [1] + [sq[2 * d - j] for j in range(1, ctx["l"] + 1)]


def all_character_psi(q, d):
    """psi_{2d}(chi) for every character (flat index), trivial character included (= q^{2d})."""
    l = d - 1
    ctx = setup(q, l)
    N = q ** l
    shape = ctx["shape"]
    C = []
    for kdeg in range(0, l):
        ind = _indices_degree(kdeg, l, q, ctx["p"], ctx["k"], ctx["A"], ctx["M"], ctx["NEG"],
                              ctx["FROB"], ctx["FINV"], ctx["axis_of"], ctx["orders"], ctx["strides"])
        arr = np.zeros(N, np.complex128)
        np.add.at(arr, ind, 1.0)
        C.append(np.fft.fftn(arr.reshape(shape)).reshape(N))
    n_target = 2 * d
    psi = [None] * (n_target + 1)
    for n in range(1, n_target + 1):
        acc = n * C[n] if n < l else np.zeros(N, np.complex128)
        for kk in range(max(1, n - l + 1), n):
            acc = acc - psi[kk] * C[n - kk]
        psi[n] = acc
    top = psi[n_target].copy()
    top[0] = float(q) ** n_target
    return top, ctx


def all_interval_psi(q, d, work_dir=None, keep_L=False):
    """
    Psi(x) for every class x (flat index), as float64. If work_dir is given, the L-coefficient
    arrays are stored in memmaps there. If keep_L, also return the list of coefficient arrays.
    """
    l = d - 1
    ctx = setup(q, l)
    N = q ** l
    shape = ctx["shape"]
    try:
        import scipy.fft as sfft
    except ImportError:  # pragma: no cover
        sfft = None
    C = []
    for kdeg in range(0, l):
        ind = _indices_degree(kdeg, l, q, ctx["p"], ctx["k"], ctx["A"], ctx["M"], ctx["NEG"],
                              ctx["FROB"], ctx["FINV"], ctx["axis_of"], ctx["orders"], ctx["strides"])
        arr = np.zeros(N, np.complex128)
        np.add.at(arr, ind, 1.0)
        del ind
        if sfft is not None:
            F = sfft.fftn(arr.reshape(shape), overwrite_x=True, workers=-1).reshape(N)
        else:
            F = np.fft.fftn(arr.reshape(shape)).reshape(N)
        del arr
        if work_dir is not None:
            mm = np.memmap(os.path.join(work_dir, f"c{kdeg}.dat"), dtype=np.complex128, mode="w+", shape=(N,))
            mm[:] = F
            del F
            C.append(mm)
        else:
            C.append(F)
    n_target = 2 * d
    top = np.empty(N, np.complex128)
    chunk = 1 << 21
    for s0 in range(0, N, chunk):
        s1 = min(N, s0 + chunk)
        c = [np.asarray(C[t][s0:s1]) for t in range(l)]
        psi = [None] * (n_target + 1)
        for n in range(1, n_target + 1):
            acc = n * c[n] if n < l else np.zeros(s1 - s0, np.complex128)
            for kk in range(max(1, n - l + 1), n):
                acc = acc - psi[kk] * c[n - kk]
            psi[n] = acc
        top[s0:s1] = psi[n_target]
    top[0] = float(q) ** n_target
    if work_dir is not None:
        C = [None] * len(C)  # release the memmaps before the last transform
    if sfft is not None:
        Psi = sfft.ifftn(top.reshape(shape), overwrite_x=True, workers=-1).reshape(N).real
    else:
        Psi = np.fft.ifftn(top.reshape(shape)).reshape(N).real
    out = (Psi, ctx)
    if keep_L:
        out = out + (C,)
    return out
