"""
Experiment 7 -- zeros of all Hayes L-functions L(z, chi), chi a nontrivial character of G_{d-1},
for fixed q, compared with random unitary matrices (CUE).

For each chi, L(z, chi) = sum_{k < d-1} c_k(chi) z^k (c_0 = 1) is computed by hayes_fft_fq.
Its inverse roots omega satisfy |omega| = sqrt(q) or |omega| = 1 (Weil). We record how many of
each kind occur, and for the "nontrivial" ones the angles theta = arg(omega / sqrt(q)).
Statistics, for the characters whose L-function has the generic number N of nontrivial zeros:
  * form factor  F(n) = mean_chi |sum_i exp(i n theta_i)|^2,  CUE prediction min(n, N);
  * nearest-neighbour spacings of the eigenangles, normalized to mean 1, against CUE(N).

Outputs data/zero_stats_summary.csv, data/zero_stats_formfactor.csv, data/zero_stats_spacing.csv
"""
import argparse
import csv
import math
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hayes_fft_fq as H  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
CASES = [(3, 12), (2, 20), (5, 9), (7, 8), (4, 10), (3, 14)]
RNG = np.random.default_rng(20261006)


def inverse_roots(C, idx):
    """Inverse roots of L(z) = sum_k C[k][idx] z^k for a batch of characters (same exact degree m).
    z^m L(1/z) = sum_k c_k z^{m-k} is monic (c_0 = 1); its roots are the inverse roots. np.roots
    (balanced companion matrix) is used per character for numerical robustness."""
    coeffs = np.stack([np.asarray(C[k][idx]) for k in range(len(C))], axis=1)  # (batch, m+1)
    out = np.empty(coeffs.shape, np.complex128)[:, 1:]
    for r in range(coeffs.shape[0]):
        out[r] = np.roots(coeffs[r])  # descending powers c_0, c_1, ..., c_m
    return out


def conductor_exponents(ctx):
    """m(chi) for every character (flat index): the least m such that chi is trivial on
    {x = 1 mod u^m}. That kernel is generated by the p^{a}-th powers of the generators 1 + omega_i u^j
    with j p^a >= m, so chi_b is trivial on it iff p^{s_j - a_j(m)} divides b_{j,i} for all (j, i),
    where a_j(m) = min{a : j p^a >= m}. deg L(z, chi) = m(chi) - 2 for chi != 1."""
    p, l, shape = ctx["p"], ctx["l"], ctx["shape"]
    js = []
    for j in range(1, l + 1):
        if j % p == 0:
            continue
        for _ in range(ctx["k"]):
            js.append(j)
    N = int(np.prod([float(n) for n in shape]))
    idx = np.arange(N)
    coords = []
    for ax in range(len(shape)):
        coords.append((idx // ctx["strides"][ax]) % shape[ax])
    m_of = np.full(N, l + 1, np.int64)
    for m in range(l + 1, 1, -1):  # decreasing: record the smallest m for which chi is trivial on K_m
        ok = np.ones(N, bool)
        for ax, (j, n) in enumerate(zip(js, shape)):
            a = 0
            while j * p ** a < m:
                a += 1
            s = int(round(math.log(n, p)))
            need = p ** max(s - a, 0)
            ok &= (coords[ax] % need) == 0
        m_of[ok] = m - 1 if m > 2 else 1
    # m_of currently holds (largest m with chi trivial on K_m) - 1 ... recompute directly instead:
    m_of = np.full(N, 2, np.int64)
    for m in range(2, l + 2):
        trivial = np.ones(N, bool)
        for ax, (j, n) in enumerate(zip(js, shape)):
            a = 0
            while j * p ** a < m:
                a += 1
            s = int(round(math.log(n, p)))
            need = p ** max(s - a, 0)
            trivial &= (coords[ax] % need) == 0
        # chi has conductor exponent > m-1 iff not trivial on K_{m-1}; conductor = least m with trivial on K_m
        m_of[~trivial] = m + 1
    m_of[0] = 0
    return m_of


def cue_angles(N, count):
    out = []
    for _ in range(count):
        Z = (RNG.standard_normal((N, N)) + 1j * RNG.standard_normal((N, N))) / np.sqrt(2)
        Q, R = np.linalg.qr(Z)
        Q = Q * (np.diagonal(R) / np.abs(np.diagonal(R)))
        out.append(np.angle(np.linalg.eigvals(Q)))
    return np.array(out)


def spacings(angles):
    a = np.sort(np.mod(angles, 2 * np.pi), axis=1)
    N = a.shape[1]
    gaps = np.diff(np.concatenate([a, a[:, :1] + 2 * np.pi], axis=1), axis=1)
    return (gaps * N / (2 * np.pi)).ravel()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-chars", type=int, default=400000)
    args = ap.parse_args()
    summ, ff_rows, sp_rows = [], [], []
    for q, d in CASES:
        t0 = time.time()
        _, ctx, C = H.all_interval_psi(q, d, keep_L=True)
        Nchar = q ** (d - 1)
        idx = np.arange(1, Nchar)
        if idx.size > args.max_chars:
            idx = np.sort(RNG.choice(idx, size=args.max_chars, replace=False))
        l = d - 1
        # exact degree of each L-function from the conductor: deg = m(chi) - 2
        m_all = conductor_exponents(ctx)
        degs = m_all[idx] - 2
        # numerical check of the degree: leading coefficient nonzero, higher ones zero
        absc = np.stack([np.abs(np.asarray(C[k][idx])) for k in range(l)], axis=1)
        lead_ok = int(np.sum(absc[np.arange(idx.size), np.maximum(degs, 0)] < 1e-6))
        high_bad = int(np.sum([(absc[r, degs[r] + 1:] > 1e-6).any() for r in range(idx.size)]))
        cond_counts = {int(m): int(np.sum(m_all[1:] == m)) for m in np.unique(m_all[1:])}
        kinds = {}
        angle_sets = []
        off_circle = 0
        max_dev = 0.0
        for deg in np.unique(degs):
            sel = idx[degs == deg]
            if deg <= 0:
                kinds[(0, 0)] = kinds.get((0, 0), 0) + sel.size
                continue
            Csub = [C[k] for k in range(deg + 1)]
            roots = inverse_roots(Csub, sel)
            mod = np.abs(roots)
            nontriv = np.abs(mod - np.sqrt(q)) < 1e-3 * np.sqrt(q)
            triv = np.abs(mod - 1) < 1e-3
            max_dev = max(max_dev, float(np.max(np.abs(mod / np.sqrt(q) - 1.0))))
            off_circle += int((~(nontriv | triv)).sum())
            nn = nontriv.sum(axis=1)
            for a, b in zip(nn, deg - nn):
                kinds[(int(a), int(b))] = kinds.get((int(a), int(b)), 0) + 1
            angle_sets.append((nn, np.angle(roots / np.sqrt(q)), nontriv))
        Ngen = max(kinds, key=lambda kk: kinds[kk])[0]
        # angles for the generic family (Ngen nontrivial zeros)
        ang = []
        for nn, angs, nt in angle_sets:
            rows = np.where(nn == Ngen)[0]
            for r in rows:
                ang.append(angs[r][nt[r]])
        ang = np.array(ang)
        n_gen = ang.shape[0]
        summ.append({"q": q, "d": d, "characters": int(idx.size), "generic_nontrivial_zeros": Ngen,
                     "generic_fraction": n_gen / idx.size,
                     "zero_types": "; ".join(f"{a}+{b}:{c}" for (a, b), c in sorted(kinds.items())),
                     "roots_off_both_circles": off_circle, "max_rel_dev_from_sqrt_q": max_dev,
                     "conductor_counts": "; ".join(f"{m}:{c}" for m, c in sorted(cond_counts.items())),
                     "conductor_counts_expected": "; ".join(f"{m}:{q ** (m - 1) - q ** (m - 2)}" for m in sorted(cond_counts)),
                     "degree_check_failures": lead_ok + high_bad,
                     "seconds": round(time.time() - t0, 1)})
        for n in range(1, 3 * Ngen + 3):
            F = float(np.mean(np.abs(np.exp(1j * n * ang).sum(axis=1)) ** 2))
            ff_rows.append({"q": q, "d": d, "N": Ngen, "n": n, "form_factor": F, "CUE": min(n, Ngen)})
        if Ngen >= 2:
            s = spacings(ang)
            sc = spacings(cue_angles(Ngen, 20000))
            bins = np.linspace(0, 3.5, 36)
            h1, _ = np.histogram(s, bins=bins, density=True)
            h2, _ = np.histogram(sc, bins=bins, density=True)
            for lo, a, b in zip(bins[:-1], h1, h2):
                sp_rows.append({"q": q, "d": d, "N": Ngen, "s_lo": round(float(lo), 3),
                                "density_data": float(a), "density_CUE": float(b)})
        print(summ[-1], flush=True)
    for name, rows in [("zero_stats_summary", summ), ("zero_stats_formfactor", ff_rows), ("zero_stats_spacing", sp_rows)]:
        with open(os.path.join(DATA, f"{name}.csv"), "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)


if __name__ == "__main__":
    main()
